FROM python:3
USER root

RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

RUN mkdir /root/html

WORKDIR /root/opt
RUN apt-get install -y vim less
RUN apt-get install -y cron

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install requests
RUN pip install pandas
RUN pip install numpy
RUN pip install SQLAlchemy
RUN pip install PyMySQL
RUN pip install timeout_decorator