CREATE TABLE TECHNICAL_BB(
    pair VARCHAR(20) NOT NULL,
    calcTime DATETIME NOT NULL,
    price double,
    SMA_15M double,
    UPR_15M double,
    LWR_15M double,
    BBB_15M double,
    BBWR_15M double,
    SMA_1H double,
    UPR_1H double,
    LWR_1H double,
    BBB_1H double,
    BBWR_1H double,
    SMA_4H double,
    UPR_4H double,
    LWR_4H double,
    BBB_4H double,
    BBWR_4H double,
    SMA_1D double,
    UPR_1D double,
    LWR_1D double,
    BBB_1D double,
    BBWR_1D double,
    PRIMARY KEY(pair,calcTime)
)